# Generated by Django 3.2.7 on 2021-09-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empl_id', models.IntegerField()),
                ('fio', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=50)),
                ('date_create', models.DateField()),
                ('salary', models.IntegerField()),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_v1.employee')),
            ],
        ),
    ]
